"""Sphinx configuration for "Process Improvement Using Data".

Originally generated by sphinx-quickstart in May 2010.
"""

import datetime
import os
import subprocess
import sys

from pygments.formatters.latex import LatexFormatter
from sphinx.highlighting import PygmentsBridge

sys.path.append(os.getcwd())
sys.path.insert(0, os.path.abspath("."))

# Minimum Sphinx version. pyproject.toml pins sphinx>=8.1.3.
needs_sphinx = "5.0"

extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.mathjax",
    "sphinxcontrib.jquery",
    "my-extensions.youtube",
    "my-extensions.datacamplite",
]

# Avoid Subresource Integrity errors for the bundled jQuery.
jquery_use_sri = False

# NOTE: MathJax path is also forced in `layout.html` (see the `{# MathJax #}` comment).

templates_path = ["_templates"]
source_suffix = {".rst": "restructuredtext"}
root_doc = "contents"
language = "en"

the_year = str(datetime.datetime.now().year)
project = "Process Improvement Using Data"
author = "Kevin Dunn"
copyright = f"2010-{the_year} {author}"
today_fmt = "%d %B %Y"

# Emit warnings for all missing references.
nitpicky = True

# Use the short Git SHA as the release identifier.
try:
    _git = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    )
    release = _git.stdout.strip()[:6]
except (subprocess.CalledProcessError, FileNotFoundError):
    release = "unknown"
version = release

exclude_patterns = [
    "_build",
    ".hg",
    "ext",
    "DELETE",
    ".venv",
    "**/.ipynb_checkpoints",
]

add_function_parentheses = True
pygments_style = "sphinx"

# These substitutions apply to every RST file
rst_prolog = """
.. meta::
   :http-equiv=X-UA-Compatible: IE=EmulateIE7
"""

rst_epilog = r"""
.. |x| replace:: :math:`\mathrm{x}`
.. |y| replace:: :math:`\mathrm{y}`
.. |z| replace:: :math:`\mathrm{z}`
.. |n| replace:: :math:`n`
.. |b0| replace:: :math:`b_0`
.. |b1| replace:: :math:`b_1`
.. |-| replace:: :math:`-`
.. |+| replace:: :math:`+`
.. |t| replace:: :math:`\mathbf{t}`
.. |T| replace:: :math:`\mathbf{T}`
.. |X| replace:: :math:`\mathbf{X}`
.. |Xraw| replace:: :math:`\mathbf{X}_\text{raw}`
.. |P| replace:: :math:`\mathbf{P}`
.. |p1| replace:: :math:`\mathbf{p}_1`
.. |T2| replace:: :math:`T^2`
.. |R| replace:: :math:`\mathbf{R}`
.. |U| replace:: :math:`\mathbf{U}`
.. |Y| replace:: :math:`\mathbf{Y}`
.. |W| replace:: :math:`\mathbf{W}`
.. |Z| replace:: :math:`\mathbf{Z}`
.. |Q2| replace:: :math:`Q^2`
.. |A| replace:: :math:`A`
.. |K| replace:: :math:`K`
.. |M| replace:: :math:`M`
.. |Cpk| replace:: C\ :sub:`pk`
.. |xdb| replace:: :math:`\overline{\overline{x}}`
"""

linkcheck_ignore = [
    r"http://dx.doi.org/.+",
    "http://www.jstor.org/pss/.+",
    "http://books.google.com/.+",
]
linkcheck_workers = 10

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  Major themes that come with
# Sphinx are currently 'default' and 'sphinxdoc'.
# html_theme = 'pyramid'

# sudo easy_install sphinx_rtd_theme
# In your conf.py file:

# pip install -U sphinx_rtd_theme
# import sphinx_rtd_theme
# html_theme = "sphinx_rtd_theme"
# html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

html_theme = "sphinx_rtd_theme_kgdmod"
html_theme_path = [
    ".",
]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = "Process Improvement using Data"

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "preface/textbook-logo-no-text-lowres.jpg"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "sphinx_rtd_theme_kgdmod/static/media/favicon.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = "%d %B %Y"

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# Leave as True: stictly speaking, the Makefile for "html" will replace the source code with
# the "text" builder's output, eliminating any comments and other details from the source.
html_copy_source = True

html_search_language = "en"

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# Permalinks (those strange characters next to headings)
html_permalinks = True
html_permalinks_icon = "¶"  # was 'Permalink'

# If nonempty, this is the file name suffix for generated HTML files. The
# default is ".html".
# You will also have to edit
# "/anaconda/lib/python2.7/site-packages/sphinx/themes/basic/static/searchtools....."
# Search for the entry "DOCUMENTATION_OPTIONS.FILE_SUFFIX" and you will see where a
# trailing "/" gets auto added. Remove that code.
#
# Also set:: var suffix = '.txt'; //DOCUMENTATION_OPTIONS.SOURCELINK_SUFFIX;
# in the "searchtools.js_t" file

html_file_suffix = ""

# Suffix for generated links to HTML files. The default is whatever
# html_file_suffix is set to; it can be set differently (e.g. to support
# different web server setups).
html_link_suffix = ""

# Output file base name for HTML help builder.
# htmlhelp_basename = ''

# Suffix for section numbers. Default: ". ". Set to " " to suppress final dot on section numbers.
html_secnumber_suffix = r". "


# -- Options for link checking -------------------------------------------------

# A list of regular expressions that match URIs that should not be checked when doing linkcheck.
linkcheck_ignore = [r"http://localhost:\d+/"]

# A timeout value, in seconds, for the linkcheck builder. Only works in Python 2.6 and higher.
# The default is to use Python’s global socket timeout.
linkcheck_timeout = 20

# The number of worker threads to use when checking links. Default is 5 threads.
linkcheck_workers = 5

# True or false, whether to check the validity of #anchors in links. Since this requires
# downloading the whole document, it’s considerably slower when enabled. Default is True.
linkcheck_anchors = True

# -- Options for LaTeX output --------------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual], toctree only).
latex_documents = [
    (
        "contents",
        "PID.tex",
        "Process Improvement Using Data",
        "Kevin Dunn",
        "manual",
        True,
    ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = html_logo

# If true, add page references after internal references. This is very useful for
# printed copies of the manual. Default is False.
latex_show_pagerefs = True

latex_additional_files = []  # 'preface.tex'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = False

# Control whether to display URL addresses. This is very useful for printed copies of the
# manual. The setting can have the following values:
# 'no' – do not display URLs (default)
# 'footnote' – display URLs in footnotes
# 'inline' – display URLs inline in parentheses
latex_show_urls = "footnote"


# Control the source code size
# http://stackoverflow.com/questions/9899283/how-do-you-change-the-code-example-font-size-in-latex-pdf-output-with-sphinx
class CustomLatexFormatter(LatexFormatter):
    def __init__(self, **options):
        super(CustomLatexFormatter, self).__init__(**options)
        self.verboptions = r"formatcom=\footnotesize,frame=lines"


PygmentsBridge.latex_formatter = CustomLatexFormatter


# _MAKETITLE = r""" """


# Commands that go at the TOC section
_TABLE_OF_CONTENTS = r"""
% ==== BEGIN CUSTOMIZED TOC ====

~\vfill
\thispagestyle{empty}
Copyright \copyright\ 2010 to \the\year\ Kevin G. Dunn

% Sphinx has decided to set this to "-2" in one of the newer versions.
% Set it "+1", which is what we are looking for
% Apparently cleared up in Sphinx 1.3.5
%\setcounter{tocdepth}{+1}

%\pagenumbering{gobble}
\tableofcontents
% \pagenumbering{gobble}
%\thispagestyle{empty}
%\pagenumbering{gobble}
\addtocontents{toc}{\protect\thispagestyle{empty}}
%\pagenumbering{gobble}
% ==== END OF CUSTOMIZED TOC ====

"""

_PREAMBLE = r"""
% ==== BEGIN CUSTOMIZED PREAMBLE ====
\usepackage{float}
\usepackage{cancel}  % to get cancelled terms
\usepackage{upquote} % to avoid quotation marks from being mangled
\usepackage{textpos} % get YouTube links outside the margin. Tthe package is in "relative" mode
\renewcommand{\PYGZsq}{TO AVOID ERROR MESSAGE}


\usepackage[]{geometry}
%\geometry{left=1.0in,width=6.5in,top=0.75in,height=9.25in,nohead,footskip=0.5in,portrait}
 \geometry{left=1.0in,width=6.5in,top=1.00in,height=9.25in,       footskip=0.5in,portrait}

\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    citecolor=black,
    filecolor=black,
    urlcolor=blue
}
%\fvset{frame=single,xleftmargin=9pt,numbersep=4pt}

% Nicer URLs
\usepackage{url}
\makeatletter
\def\Url@twoslashes{\mathchar`\/\@ifnextchar/{\kern-.2em}{}}
\g@addto@macro\UrlSpecials{\do\/{\Url@twoslashes}}
\makeatother



\renewcommand{\sectionmark}[1]%
{\markright{\MakeUppercase{\thesection.\ #1}}}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}
\fancyhf{}
\fancyfoot[C]{\thepage}
\fancyhead[RO]{}
\fancyhead[LE]{}

\fancypagestyle{plain}{
  \fancyhf{} % empty header and footer
  \renewcommand{\headrulewidth}{0pt} % ho header line
  \renewcommand{\footrulewidth}{0pt}% not footer line
  \fancyfoot[C]{\thepage}% like fancy style
}

\makeatletter
\def\@subtitle{\relax}
\newcommand{\subtitle}[1]{\gdef\@subtitle{#1}}
\makeatother



\makeatletter
\renewcommand{\releasename}{Version}
\renewcommand{\maketitle}{%
  \begin{titlepage}%
    \let\footnotesize\small
    \let\footnoterule\relax
    \rule{\textwidth}{1pt}%

    \begin{flushright}%
      % \sphinxlogo% Don't want logo here, and not this size. Manually placed it a few lines down.
      {\rm\Huge\py@HeaderFamily \@title \par}%
      \vfill
      {\LARGE\py@HeaderFamily \@author \par}
      \vfill\vfill
      \includegraphics[scale=0.35]{textbook-logo-no-text.jpg}
      \\
      {\large
       \@date \par
       \vfill
       \py@authoraddress \par
       \vfill
       {\Large\py@HeaderFamily Version: \py@release\releaseinfo \par}
      }%
    \end{flushright}%\par
    \@thanks
  \end{titlepage}%
  \setcounter{footnote}{0}%
  \let\thanks\relax\let\maketitle\relax
  %\gdef\@thanks{}\gdef\@author{}\gdef\@title{}
}
\makeatother



\fancypagestyle{normal}{
  \fancyhf{}
  \fancyfoot[LE,RO]{{\py@HeaderFamily\thepage}}
  \fancyfoot[LO]{{\py@HeaderFamily\nouppercase{\rightmark}}}
  \fancyfoot[RE]{{\py@HeaderFamily\nouppercase{\leftmark}}}
  \fancyhead[LE,RO]{{\py@HeaderFamily \@title, \py@release}}
  \renewcommand{\headrulewidth}{0.4pt}
  \renewcommand{\footrulewidth}{0.4pt}
}

\makeatletter
  % Use \pagestyle{normal} as the primary pagestyle for text.
  \fancypagestyle{normal}{
    \fancyhf{}
    \fancyfoot[LE,RO]{{\py@HeaderFamily\thepage}}
    \fancyfoot[LO]{{\py@HeaderFamily\nouppercase{\rightmark}}}
    \fancyfoot[RE]{{\py@HeaderFamily\nouppercase{\leftmark}}}
    \fancyhead[LE]{{\py@HeaderFamily \@title}} % before: \py@HeaderFamily \@title, \py@release
    \fancyhead[RO]{{\py@HeaderFamily \py@release}} % before: \py@HeaderFamily \@title, \py@release
    \renewcommand{\headrulewidth}{0.4pt}
    \renewcommand{\footrulewidth}{0.4pt}
  }
  % Update the plain style so we get the page number & footer line,
  % but not a chapter or section title.  This is to keep the first
  % page of a chapter and the blank page between chapters `clean.'
  \fancypagestyle{plain}{
    \fancyhf{}
    \fancyfoot[LE,RO]{{\py@HeaderFamily\thepage}}
    \renewcommand{\headrulewidth}{0pt}
    \renewcommand{\footrulewidth}{0.4pt}
  }

  \definecolor{VerbatimColor}{rgb}{1,1,1}
  \definecolor{VerbatimBorderColor}{rgb}{1,1,1}


  % Better style: use ragged right (based on https://tufte-latex.github.io/tufte-latex/)
  \raggedright
  % \RaggedRight allows hyphenation
  \RequirePackage{ragged2e}
  \setlength{\RaggedRightRightskip}{\z@ plus 0.08\hsize}


  % Set the font sizes and baselines to match Tufte's books
  \renewcommand\normalsize{%
     \@setfontsize\normalsize\@xpt{14}%
     \abovedisplayskip 10\p@ \@plus2\p@ \@minus5\p@
     \abovedisplayshortskip \z@ \@plus3\p@
     \belowdisplayshortskip 6\p@ \@plus3\p@ \@minus3\p@
     \belowdisplayskip \abovedisplayskip
     \let\@listi\@listI}
  \normalbaselineskip=14pt
  \normalsize
  \renewcommand\small{%
     \@setfontsize\small\@ixpt{12}%
     \abovedisplayskip 8.5\p@ \@plus3\p@ \@minus4\p@
     \abovedisplayshortskip \z@ \@plus2\p@
     \belowdisplayshortskip 4\p@ \@plus2\p@ \@minus2\p@
     \def\@listi{\leftmargin\leftmargini
                 \topsep 4\p@ \@plus2\p@ \@minus2\p@
                 \parsep 2\p@ \@plus\p@ \@minus\p@
                 \itemsep \parsep}%
     \belowdisplayskip \abovedisplayskip
  }
  \renewcommand\footnotesize{%
     \@setfontsize\footnotesize\@viiipt{10}%
     \abovedisplayskip 6\p@ \@plus2\p@ \@minus4\p@
     \abovedisplayshortskip \z@ \@plus\p@
     \belowdisplayshortskip 3\p@ \@plus\p@ \@minus2\p@
     \def\@listi{\leftmargin\leftmargini
                 \topsep 3\p@ \@plus\p@ \@minus\p@
                 \parsep 2\p@ \@plus\p@ \@minus\p@
                 \itemsep \parsep}%
     \belowdisplayskip \abovedisplayskip
  }
  \renewcommand\scriptsize{\@setfontsize\scriptsize\@viipt\@viiipt}
  \renewcommand\tiny{\@setfontsize\tiny\@vpt\@vipt}
  \renewcommand\large{\@setfontsize\large\@xipt{15}}
  \renewcommand\Large{\@setfontsize\Large\@xiipt{16}}
  \renewcommand\LARGE{\@setfontsize\LARGE\@xivpt{18}}
  \renewcommand\huge{\@setfontsize\huge\@xxpt{30}}
  \renewcommand\Huge{\@setfontsize\Huge{24}{36}}

  \setlength\leftmargini   {1pc}
  \setlength\leftmarginii  {1pc}
  \setlength\leftmarginiii {1pc}
  \setlength\leftmarginiv  {1pc}
  \setlength\leftmarginv   {1pc}
  \setlength\leftmarginvi  {1pc}
  \setlength\labelsep      {.5pc}
  \setlength\labelwidth    {\leftmargini}
  \addtolength\labelwidth{-\labelsep}


\makeatother
% ==== END OF CUSTOMIZED PREAMBLE ====
"""

# % Redefine these colors to your liking in the preamble.
# \definecolor{TitleColor}{rgb}{0,0,0}
# \definecolor{InnerLinkColor}{rgb}{0.208,0.374,0.486}
# \definecolor{OuterLinkColor}{rgb}{0.216,0.439,0.388}
# % Redefine these colors to something not white if you want to have colored
# % background and border for code examples.
# \definecolor{VerbatimColor}{rgb}{1,1,1}
# \definecolor{VerbatimBorderColor}{rgb}{1,1,1}
#
# \makeatletter
# % Notices / Admonitions
# %
# \newcommand{\py@veryheavybox}{
#   \setlength{\fboxrule}{2pt}
#   \setlength{\fboxsep}{7pt}
#   \setlength{\py@noticelength}{\linewidth}
#   \addtolength{\py@noticelength}{-2\fboxsep}
#   \addtolength{\py@noticelength}{-2\fboxrule}
#   \setlength{\shadowsize}{3pt}
#   \Sbox
#   \minipage{\py@noticelength}
# }
# \newcommand{\py@endveryheavybox}{
#   \endminipage
#   \endSbox
#   \fbox{\TheSbox}
# }
# \renewcommand{\py@noticestart@warning}{\py@veryheavybox}
# \renewcommand{\py@noticeend@warning}{\py@endveryheavybox}
# \renewcommand{\py@noticestart@note}{\py@heavybox}
# \renewcommand{\py@noticeend@note}{\py@endheavybox}
# \makeatother
#
# %\sloppy
# \pagestyle{plain}

latex_elements = {
    "papersize": "a4paper",  # paper size ('letter' or 'a4paper').
    "pointsize": "11pt",  # font size ('10pt', '11pt' or '12pt')
    "fontpkg": "\\usepackage{palatino}",
    "preamble": _PREAMBLE,
    "figure_align": "H",  # put figures where told
    # Bjarne (default), Lenny” (OK), “Glenn” (nice), “Conny” and “Rejne”,
    "fncychap": "\\usepackage[Glenn]{fncychap}",
    "tableofcontents": _TABLE_OF_CONTENTS,
    "inputenc": "\\usepackage[utf8]{inputenc}",  # default
    "fontenc": "\\usepackage[T1]{fontenc}",  # default
    # 'maketitle': '\\maketitle',   # default
    # override to generate index differently or append some content after the index
    "printindex": "\\printindex",
    "releasename": "",
    #   'docclass' 'classoptions' 'title' 'date' 'release' 'author' 'logo' 'releasename'
    #   'makeindex' 'shorthandoff'
}

# -- Options for Epub output ---------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = "Process Improvement Using Data"
epub_author = "Kevin Dunn"
epub_publisher = ""
epub_copyright = the_year + ""

# The language of the text. It defaults to the language option
# or en if the language is not set.
epub_language = "en"

# The scheme of the identifier. Typical schemes are ISBN or URL.
# epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
# epub_identifier = ''

# A unique identification for the text.
# epub_uid = ''

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
# epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
# epub_post_files = []

# A list of files that should not be packed into the epub file.
# epub_exclude_files = []

# The depth of the table of contents in toc.ncx.
# epub_tocdepth = 3
