# -*- coding: utf-8 -*-
#
# PID documentation build configuration file, created by
# sphinx-quickstart on Tue May 11 18:39:16 2010.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.
# From Sphinx
import sys, os
sys.path.append(os.getcwd())

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.append(os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.

# Sphinx extensions
extensions = ['sphinx.ext.todo', 'sphinx.ext.pngmath', 'sphinx.ext.ifconfig']
# Custom extensions
sys.path.append(os.path.abspath(os.getcwd()))
extensions.append('q-and-a')
if os.path.exists('ucomment-extension'):
    extensions.append('ucomment-extension')
    html_translator_class = 'ucomment-extension.ucomment_html_translator'

# Point to your Django application, which contains all the other settings required.
ucomment = {}
ucomment['django_application_path'] = '/home/kevindunn/webapps/pid_connectmv_com/pidbook/ucommentapp/'

# MathJax settings:
extensions.append('mathjax')
#mathjax_path = ' '

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'contents'

# General information about the project.
project = u'Process Improvement using Data'
copyright = u'2010, Kevin Dunn'
today_fmt = '%B %Y'

# Emits warnings for all missing references.
nitpicky = False

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.5'
# The full version, including alpha/beta/rc tags.
release = '0.5'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', '.hg']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# These substitutions apply to every RST file
rst_prolog = """
.. meta:: 
   :http-equiv=X-UA-Compatible: IE=EmulateIE7
"""

rst_epilog = """
.. |x| replace:: :math:`\mathrm{x}`
.. |y| replace:: :math:`\mathrm{y}`
.. |z| replace:: :math:`\mathrm{z}`
.. |n| replace:: :math:`n`
.. |b0| replace:: :math:`b_0`
.. |b1| replace:: :math:`b_1`
.. |-| replace:: :math:`-`
.. |+| replace:: :math:`+`
.. |t| replace:: :math:`\mathbf{t}`
.. |T| replace:: :math:`\mathbf{T}`
.. |X| replace:: :math:`\mathbf{X}`
.. |Xraw| replace:: :math:`\mathbf{X}_\\text{raw}`
.. |P| replace:: :math:`\mathbf{P}`
.. |p1| replace:: :math:`\mathbf{p}_1`
.. |T2| replace:: :math:`T^2`
.. |W*| replace:: :math:`\mathbf{W*}`
.. |w*| replace:: :math:`\mathbf{w*}`
.. |U| replace:: :math:`\mathbf{U}`
.. |Y| replace:: :math:`\mathbf{Y}`
.. |W| replace:: :math:`\mathbf{W}`
.. |Q2| replace:: :math:`Q^2`
.. |A| replace:: :math:`A`
.. |K| replace:: :math:`K`
.. |M| replace:: :math:`M`
.. |Cpk| replace:: C\ :sub:`pk`
.. |xdb| replace:: :math:`\Bar{\Bar{x}}`
"""

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  Major themes that come with
# Sphinx are currently 'default' and 'sphinxdoc'.
html_theme = 'default'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
html_use_smartypants = False

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# Permalinks (those strange characters next to headings)
html_add_permalinks = None

# If nonempty, this is the file name suffix for generated HTML files. The
# default is ".html".
html_file_suffix = ''

# Suffix for generated links to HTML files. The default is whatever
# html_file_suffix is set to; it can be set differently (e.g. to support
# different web server setups).
html_link_suffix = ''

# Output file base name for HTML help builder.
#htmlhelp_basename = ''


# -- Options for LaTeX output --------------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual], toctree only).
latex_documents = [
  ('contents', 'PID.tex', 'Process Improvement using Data', u'Kevin Dunn',
   'manual', True),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = False

#_MAKETITLE = r""" """

# Commands that go at the TOC section
_TABLE_OF_CONTENTS = r"""
% ==== BEGIN CUSTOMIZED TOC ====
%\renewcommand{\baselinestretch}{0.95}                   % Use 1.25 line spacing
%\small\normalsize                                       % Change font sizes down and back up to active the line spacing
                                                        % See page 47 in the LaTeX manual for this trick
%\setcounter{tocdepth}{2}
\tableofcontents
%\renewcommand{\baselinestretch}{1.00}                   % Use 1.25 line spacing
%\small\normalsize                                       % Change font sizes down and back up to active the line spacing
%                                                        % See page 47 in the LaTeX manual for this trick
% ==== END OF CUSTOMIZED TOC ====
"""

_PREAMBLE = r"""
% ==== BEGIN CUSTOMIZED PREAMBLE ====
\usepackage{float}

\usepackage[]{geometry}
%\geometry{left=1.0in,width=6.5in,top=0.75in,height=9.25in,nohead,footskip=0.5in,portrait}
 \geometry{left=1.0in,width=6.5in,top=1.00in,height=9.25in,       footskip=0.5in,portrait}

\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    citecolor=black,
    filecolor=black,
    urlcolor=blue
}
%\fvset{frame=single,xleftmargin=9pt,numbersep=4pt}

\renewcommand{\sectionmark}[1]%
{\markright{\MakeUppercase{\thesection.\ #1}}}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}
\fancyhf{}
\fancyfoot[C]{\thepage}
\fancyhead[RO]{}
\fancyhead[LE]{}

\fancypagestyle{plain}{
  \fancyhf{} % empty header and footer
  \renewcommand{\headrulewidth}{0pt} % ho header line
  \renewcommand{\footrulewidth}{0pt}% not footer line
  \fancyfoot[C]{\thepage}% like fancy style
}

\makeatletter
\def\@subtitle{\relax}
\newcommand{\subtitle}[1]{\gdef\@subtitle{#1}}
\makeatother

\makeatletter
\renewcommand{\maketitle}{%
  \begin{titlepage}%
    \let\footnotesize\small
    \let\footnoterule\relax
    \rule{\textwidth}{1pt}%
    \ifsphinxpdfoutput
      \begingroup
      % This \def is required to deal with multi-line authors; it
      % changes \\ to ', ' (comma-space), making it pass muster for
      % generating document info in the PDF file.
      \def\\{, }
      \pdfinfo{
        /Author (\@author)
        /Title (\@title)
      }
      \endgroup
    \fi
    \begin{flushright}%
      \sphinxlogo%
      {\rm\Huge\py@HeaderFamily \@title \par}%
      {\em\LARGE\py@HeaderFamily \py@release\releaseinfo \par}
      \vfill
      {\LARGE\py@HeaderFamily \@author \par}
      \vfill\vfill
      {\large
       \@date \par
       \vfill
       \py@authoraddress \par
      }%
    \end{flushright}%\par
    \@thanks
  \end{titlepage}%
  \setcounter{footnote}{0}%
  \let\thanks\relax\let\maketitle\relax
  %\gdef\@thanks{}\gdef\@author{}\gdef\@title{}
}
\makeatother

% ==== END OF CUSTOMIZED PREAMBLE ====
"""

# % Redefine these colors to your liking in the preamble.
# \definecolor{TitleColor}{rgb}{0,0,0}
# \definecolor{InnerLinkColor}{rgb}{0.208,0.374,0.486}
# \definecolor{OuterLinkColor}{rgb}{0.216,0.439,0.388}
# % Redefine these colors to something not white if you want to have colored
# % background and border for code examples.
# \definecolor{VerbatimColor}{rgb}{1,1,1}
# \definecolor{VerbatimBorderColor}{rgb}{1,1,1}
#
# \makeatletter
# % Notices / Admonitions
# %
# \newcommand{\py@veryheavybox}{
#   \setlength{\fboxrule}{2pt}
#   \setlength{\fboxsep}{7pt}
#   \setlength{\py@noticelength}{\linewidth}
#   \addtolength{\py@noticelength}{-2\fboxsep}
#   \addtolength{\py@noticelength}{-2\fboxrule}
#   \setlength{\shadowsize}{3pt}
#   \Sbox
#   \minipage{\py@noticelength}
# }
# \newcommand{\py@endveryheavybox}{
#   \endminipage
#   \endSbox
#   \fbox{\TheSbox}
# }
# \renewcommand{\py@noticestart@warning}{\py@veryheavybox}
# \renewcommand{\py@noticeend@warning}{\py@endveryheavybox}
# \renewcommand{\py@noticestart@note}{\py@heavybox}
# \renewcommand{\py@noticeend@note}{\py@endheavybox}
# \makeatother
#
# %\sloppy
# \pagestyle{plain}

latex_elements = {
     'papersize': 'letterpaper',  # paper size ('letter' or 'a4paper').
     'pointsize': '11pt',         # font size
     'fontpkg': '\\usepackage{palatino}',
     'preamble': _PREAMBLE,
     #'maketitle': _MAKETITLE,
     'tableofcontents': _TABLE_OF_CONTENTS
}

# -- Options for Epub output ---------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = 'Process Improvement using Data'
epub_author = u'Kevin Dunn'
epub_publisher = u'Some Company, Inc.'
epub_copyright = u'2010, Some Company, Inc.'

# The language of the text. It defaults to the language option
# or en if the language is not set.
epub_language = 'en'

# The scheme of the identifier. Typical schemes are ISBN or URL.
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#epub_identifier = ''

# A unique identification for the text.
#epub_uid = ''

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_post_files = []

# A list of files that should not be packed into the epub file.
#epub_exclude_files = []

# The depth of the table of contents in toc.ncx.
#epub_tocdepth = 3
