# justfile — Just (https://just.systems) recipes for building the book.
#
# An optional, friendlier alternative to the Makefile: run `just` with no
# arguments to see the menu. The Makefile stays the canonical entry point and
# is what CI uses; this file mirrors its build commands so `just` can be
# trialled as a stand-alone replacement. See CONTRIBUTING.md for how to
# install `just`.
#
# Not ported: the Makefile's PAPER=a4|letter override (conf.py already pins
# a4) and the rarely-used Sphinx builders (dirhtml, json, ...).

builddir := "_build"
sphinxbuild := "uv run sphinx-build"
# -E rebuilds every file from scratch; -j auto parallelises across CPUs.
allopts := "-d " + builddir + "/doctrees -E -j auto ."

# List the available recipes (runs when `just` is given no arguments).
default:
    @{{just_executable()}} --list

# Install uv if missing, then sync the Python dependencies.
install:
    @command -v uv >/dev/null 2>&1 || curl -LsSf https://astral.sh/uv/install.sh | sh
    uv python install
    uv sync
    @command -v latexmk >/dev/null 2>&1 || echo "WARNING: latexmk not found — 'just pdf' will not work."

alias setup := install

# Install the pre-commit git hook.
pre-commit-install:
    uvx pre-commit install

# Run every pre-commit hook over the whole tree.
pre-commit:
    uvx pre-commit run --all-files

# Build the HTML book (also builds text and runs Pagefind for search).
html:
    {{sphinxbuild}} -b html {{allopts}} {{builddir}}/html
    {{sphinxbuild}} -b text {{allopts}} {{builddir}}/text
    cp -R {{builddir}}/text/* {{builddir}}/html/_sources/
    npx -y pagefind --site {{builddir}}/html --glob "**"
    printf '<!DOCTYPE html>\n<html><head><meta http-equiv="refresh" content="0; url=contents"><link rel="canonical" href="contents"></head><body><a href="contents">Redirecting to contents…</a></body></html>\n' > {{builddir}}/html/index.html

# Build the plain-text output.
text:
    {{sphinxbuild}} -b text {{allopts}} {{builddir}}/text

# Build the LaTeX sources only, without running pdflatex.
latex:
    {{sphinxbuild}} -b latex {{allopts}} {{builddir}}/latex
    cp preface/*.png preface/*.jpg {{builddir}}/latex

# Build the PDF — needs LaTeX (latexmk).
pdf:
    @command -v latexmk >/dev/null 2>&1 || { echo "ERROR: latexmk not found."; exit 1; }
    {{sphinxbuild}} -b latex {{allopts}} {{builddir}}/latex
    cp preface/*.png preface/*.jpg {{builddir}}/latex
    # _build/latex/Makefile is generated by Sphinx; `make all-pdf` drives latexmk.
    make -C {{builddir}}/latex all-pdf
    @echo "PDF built at {{builddir}}/latex/PID.pdf"

# Build the EPUB.
epub:
    {{sphinxbuild}} -b epub {{allopts}} {{builddir}}/epub

# Build the HTML, PDF and EPUB outputs.
all: html pdf epub

# Check every external link.
linkcheck:
    {{sphinxbuild}} -b linkcheck -d {{builddir}}/doctrees -E . {{builddir}}/linkcheck

# Serve the built HTML at http://localhost:8080.
serve:
    uvx python start_server.py

# Remove build artifacts.
clean:
    rm -rf {{builddir}}
    find . -name '*.pyc' -exec rm -f {} +
    find . -name '*.pyo' -exec rm -f {} +
    find . -name '*~' -exec rm -f {} +
    find . -name '__pycache__' -exec rm -fr {} +
    find . -name '*.egg-info' -exec rm -fr {} +
    find . -name '*.egg' -exec rm -f {} +

# Like clean, but also remove the venv and lockfile.
clean-all: clean
    rm -rf .venv/ lib/ lib64/ bin/
    rm -f uv.lock
