# Data generated by: rf(50, 10, 10)*100+4000
# 4087 4107 4069 4023 4187 4330 4064 4097 4144 4055 4098 4227 4140 4124 4368 4087 4115 4108 4216 4030 4206 4150 4137 4181 4073 4093 4117 4223 4151 4070 4065 4090 4308 4059 4064 4055 4083 4112 4054 4252 4137 4120 4036 4145 4022 4123 4158 4064 4068 4174
# Bins: 	4000 4050 4100 4150 4200 4250 4300 4350 4400
# Counts:	4 19 14  5  4  1  2  1
# Mids: 	4025 4075 4125 4175 4225 4275 4325 4375

# mean(data) = 4125.32
# Surrogate mean: sum(mids*counts)/50 = 4127
# sd(data) = 77.1964
# Surrogate sd about surrogate mean: sqrt(sum(a$counts*(a$mids-m)^2)/(50-1)) = 78.86956


bin.centers <- c(4025, 4075, 4125, 4175, 4225, 4275, 4325, 4375)
bin.counts <- c(4, 19, 14,  5,  4,  1,  2,  1)
N <- 50
e.mean.est <- sum(bin.centers * bin.counts)/N                        # 4127
e.sd.est <- sqrt(sum(bin.counts*(bin.centers - e.mean.est)^2)/(N-1)) # 78.9


bitmap('../images/bulb-energy-barplot.png', type="png256", width=7, height=7, res=250, pointsize=14) 
bins.centers <- c(4025, 4075, 4125, 4175, 4225, 4275, 4325, 4375)
bins.counts <- c(4, 19, 14,  5,  4,  1,  2,  1)
barplot(bins.counts, names.arg=bins.centers, ylab="Number of bulbs (N=50)", xlab="Energy required over 24 hours (W.h)", col="White", ylim=c(0,20), cex.lab=1.5, cex.main=1.8, lwd=2, cex.sub=1.8, cex.axis=1.8)
dev.off()
